### ISSUE TITLE
Multi-namespace schemas and flattened schemas

### ISSUE THREAD

**Issue by kristiank** [holloway/doctored#11]
Hello!

It says Doctored can't handle XSD ``<include>``s and that schemas has to be flattened before. I haven't used nor experimented with XMLSpy, but as far as I can read from it's documentation, it flattens only the ``<included>`` schema documents. Since it doesn't mention ``<import>``ing schemas, I ask you directly -- is importing handled by Doctored? And what about ``<redefine>`` and ``<override>`` directives?

Is the flattening done before run-time primarily for better performance (less network requests and processing), or is it just something not yet implemented? I'm asking because I'm writing an utility in XQuery for this kind of all-inclusive flattening (or combining) of XML Schemas and perhaps I could port it or parts of it to javascript.

I'm writing the utility for being able to serve our schemas flattened to Doctored directly from our XML database, thus not needing two versions of our schemas. But we need support for ``<import>``ing of namespaces in our schemas.

Thank you.

**Comment by holloway** [comment]
Hi, the flattening is done because external files aren't supported by the XML validator library that's being used (xmllint compiled via emscripten to asm.js). So this applies to <include> and <import> etc. Thanks for noticing that -- I'll update the docs accordingly.

**Comment by holloway** [comment]
docs here fyi https://github.com/holloway/doctored/blob/master/doctored/schemas/README.md
